query GrabEmoteSet($emoteID: Id!) {
  emoteSets {
    emoteSet(id: $emoteID) {
      emotes {
        items {
          emote {
            id
            defaultName
            aspectRatio
            flags {
              animated
              defaultZeroWidth
            }
            images {
              url
            }
          }
        }
      }
    }
  }
}